export const translate = {
  en: {
    app_title: "Next Generation Armenia",
    menu_teachers: "Teachers",
    menu_donor: "Donors",
    menu_about_us: "About us",
    menu_contact_us: "Contact us",
    menu_blog: "blog",
    sign_in: "Sign In",
    welcome: "Welcome Back!",
    email_placeholder: "Email",
    password_placeholder: "Password",
    confirm_password: "Confirm Password",
    email_valid: "Email is not a correct",
    password_valid: "Password is not a correct",
    forgot_password: "Forgot Password?",
    recover_pass_success: "You've successfully recovered your password",
    register_as: "Register as a",
    its_quick_easy: "It’s quick and easy.",
    regist_name: "Name",
    regis_name_error: "Name is required",
    regist_last_name: "Last Name",
    regis_last_name_error: "Last Name is required",
    regist_phone_error: "Phone number is not correct",
    regist_region: "Region",
    regist_region_error: "Region is required",
    regist_city: "City, Village",
    regist_city_error: "City, Village is required",
    regist_school: "School",
    regist_school_error: "School is required",
    regist_subject: "Subject",
    regist_subject_error: "Subject is required",
    regist_grade: "Grade",
    regist_grade_error: "Grade is required",
    regist_confirm_pass: "Passwords don't match",
    regist_pass_error:"Password is too short",
    regist_as_a_donor: "Register as a Donor",
    regist_as_a_teacher: "Register as a Teacher",
    ok:"Ok",
    regist_last_name_error:"Last name is required",
    name_dose_have_number:"The name is not a correct",
    select_code_placeholder:"Select Code",
    regist_cencel:"If you leave this page now, all your progress will be lost",
    continu_registration:"Continue registration",
    leave_registration:"Leave anyway",
    verify_account:"Verify Account",
    email_velify:"Please check your email and enter the recovery code",
    verify_code_placeholder:"Code",
    regist_country:"Сountry",
    regist_state:"Region/State",
    regist_donor_city:"City",
    regist_country_error:"Сountry is required",
    welcome_in_page_teachers:"Welcome in page teachers",
    welcome_in_page_donors:"Welcome in page donors",
    welcome_in_page_contact_us:"Welcome in page contact us",
    welcome_in_page_about_us:"Welcome in page about us",
    welcome_in_page_blog:"Welcome in page blog",
    you_are_welcome:" You Are Welcome !!!",
    enter_email_or_recovery_code:"Please enter your email to receive a recovery code",
    recover_password:"Recover Password",
    send:"Send",
    resend_code:"Resend code",

    verify_code_error:"Verification code error. Try again.",
    done:"Done"
  },
  hy: {
    app_title: "Հաջորդ սերունդ Հայաստան",
    menu_teachers: "Ուսուցիչներ",
    menu_donor: "Դոնորներ",
    menu_about_us: "Մեր մասին",
    menu_contact_us: "Կապվեք մեզ հետ",
    menu_blog: "բլոգ",
    sign_in: "Մուտք",
    welcome: "Բարի վերադարձ!",
    email_placeholder: "Էլ. փոստ",
    password_placeholder: "Գաղտնաբառը",
    confirm_password: "Հաստատել գաղտնաբառը",
    email_valid: "Էլ. փոստը ճիշտ չէ",
    password_valid: "Գաղտնաբառը ճիշտ չէ",
    forgot_password: "Մոռացել եք գաղտնաբառը?",
    recover_pass_success: "Դուք հաջողությամբ վերականգնել եք ձեր գաղտնաբառը",
    register_as: "Գրանցվել որպես",
    regist_name: "Անուն",
    regis_name_error: "Անունը պարտադիր է",
    regist_last_name: "Ազգանուն",
    regist_region: "Տարածաշրջան",
    regist_city: "Քաղաք, գյուղ",
    regist_school: "Դպրոց",
    regist_subject: "Առարկա",
    regist_grade: "Դասարան",
    regis_last_name_error: "Ազգանունը պարտադիր է",
    regist_phone_error: "Հեռախոսահամարը ճիշտ չէ",
    regist_region_error: "Տարածաշրջանը պարտադիր է",
    regist_city_error: "Պահանջվում է քաղաք, գյուղ",
    regist_school_error: "Դպրոցը պարտադիր է",
    regist_subject_error: "Առարկան պարտադիր է",
    regist_grade_error: "Դասարանը պարտադիր է",
    regist_confirm_pass: "Գաղտնաբառերը չեն համընկնում",
    regist_as_a_donor:"Գրանցվեք որպես դոնոր",
    regist_as_a_teacher: "Գրանցվեք որպես ուսուցիչ",
    ok:"Հաջորդ",
    select_code_placeholder:"Ընտրեք կոդը",
    regist_cencel:"Եթե հիմա լքեք այս էջը, ձեր ամբողջ առաջընթացը կկորչի",
    continu_registration:"Շարունակել գրանցումը",
    leave_registration:"Ինչևէ, հեռացիր",
    verify_account:"Հաստատեք հաշիվը",
    regist_pass_error:"Գաղտնաբառը չափազանց կարճ է",
    email_velify:"Խնդրում ենք ստուգել ձեր էլ․ հասցեն և մուտքագրել վերականգնման կոդը",
    verify_code_placeholder:"Կոդ",
    regist_country:"Երկիր",
    regist_state:"Տարածաշրջան/նահանգ",
    regist_donor_city:"Քաղաք",
    regist_last_name_error:"Ազգանունը պարտադիր է",
    name_dose_have_number:"Անունը ճիշտ չէ",
    regist_country_error:"Երկիրը պարտադիր է",
    welcome_in_page_teachers:"Բարի գալուստ ուսուցիչներ էջ",
    welcome_in_page_donors:"Բարի գալուստ նվիրատուներ էջ",
    welcome_in_page_contact_us:"Բարի գալուստ կապվեք մեզ հետ էջ",
    welcome_in_page_about_us:"Բարի գալուստ մեր մասին էջ",
    welcome_in_page_blog:"Բարի գալուստ բլոգ էջ",
    you_are_welcome:"Բարի գալուստ !!!",
    enter_email_or_recovery_code:"Խնդրում ենք մուտքագրել ձեր էլ․ հասցեն՝ վերականգնման կոդը ստանալու համար",
    recover_password:"Վերականգնել գաղտնաբառը",
    send:"Ուղարկել",
    verify_code_error:"Ստուգման կոդի սխալ: Նորից փորձեք:",
    done:"Կատարած"
  },
  ru: {
    app_title: "Армения нового поколения",
    menu_teachers: "Учителя",
    menu_donor: "Доноры",
    menu_about_us: "О нас",
    menu_contact_us: "Свяжитесь с нами",
    menu_blog: "блог",
    sign_in: "Войти",
    welcome: "Добро пожаловать!",
    email_placeholder: "Электронная почта",
    password_placeholder: "Пароль",
    confirm_password: "Подтвердить Пароль",
    email_valid: "Электронная почта не является правильной",
    password_valid: "Пароль не правильный",
    forgot_password: "Забыл пароль?",
    recover_pass_success: "Вы успешно восстановили свой пароль",
    register_as: "Зарегистрируйтесь как",
    regist_name: "Имя",
    regis_name_error: "Укажите имя",
    regist_last_name: "Фамилия",
    regis_last_name_error: "Укажите Фамилия",
    regist_phone_error: "Номер телефона неверен",
    regist_region: "Область, край",
    regist_city: "Город, деревня",
    regist_school: "Школа",
    regist_subject: "Предмет",
    regist_grade: "Учебный класс",
    regist_region_error: "Укажите регион",
    regist_city_error: "Город, село обязательно",
    regist_school_error: "Школа обязательна",
    regist_subject_error: "Укажите тему",
    regist_grade_error: "Класс является обязательным",
    regist_confirm_pass: "Пароли не совпадают",
    regist_as_a_donor:"Зарегистрируйтесь как донор",
    regist_as_a_teacher: "Зарегистрироваться как учитель",
    ok:"Далее",
    select_code_placeholder:"Выберите код",
    regist_cencel:"Если вы сейчас покинете эту страницу, весь ваш прогресс будет потерян",
    continu_registration:"Continue registration",
    leave_registration:"Продолжить регистрацию",
    verify_account:"подтвердить учетную запись",
    regist_pass_error:"Пароль слишком короткий",
    email_velify:"Пожалуйста, проверьте свою электронную почту и введите код восстановления",
    verify_code_placeholder:"Код",
    regist_country:"Страна",
    regist_state:"Регион/штат",
    regist_donor_city:"Город",
    regist_last_name_error:"Требуется фамилия",
    name_dose_have_number:"Имя не верное",
    regist_country_error:"Укажите страну",
    welcome_in_page_teachers:"Добро пожаловать на страницу учителя",
    welcome_in_page_donors:"Добро пожаловать на страницу доноров",
    welcome_in_page_contact_us:"Добро пожаловать на страницу связаться с нами",
    welcome_in_page_about_us:"Добро пожаловать на страницу о нас",
    welcome_in_page_blog:"Добро пожаловать на страницу блога",
    you_are_welcome:"Добро пожаловать!!!",
    enter_email_or_recovery_code:"Пожалуйста, введите свой адрес электронной почты, чтобы получить код восстановления",
    recover_password:"Восстановить пароль",
    send:"Отправлять",
    verify_code_error:"Ошибка кода подтверждения. Попробуйте еще раз",
    done:"Сделанный"
  }
}
